apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testweb-data-protection
  namespace: mcp-experiments
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi